import { LAND_TOOLS } from "./landforming.js";
import { TRAINING_FACILITIES } from "./facilities.js";
import { EXTRA_TERRAIN } from "./terrain.js";
// Playable-milestone tuning, NOT measured retail SimGolf constants.
// Keep these explicit and replace them with observations from the original executable.
export const RULES = {
  startingCash: 50000,
  angerMood: 20, // Transitional threshold alongside zero happiness; original trigger unverified.
  angerSeconds: 20,
  angerRadius: 6,
  staffLimit: 16, // Contemporary strategy guide; later reports differ by version.
  fee: 20,
  tennisStartingMood: 60,
  arrivalRetryDelay: 1, // Retry unreachable entrances; progress gates normal arrivals.
  consultantHireCost: 300,
  consultantWage: 24,
  celebrityHireCost: 300,
  celebrityWage: 24,
  clubProHireCost: 150,
  clubProWage: 12,
  clubProRadius: 6, // Provisional greeting range.
  marshallHireCost: 300,
  marshallWage: 24,
  rangerHireCost: 150,
  rangerWage: 12,
  rangerRadius: 8,
  rangerMotivationSeconds: 20,
  rangerPaceFactor: 1.25, // Ranger coefficients await original runtime measurement.
  cartPaceFactor: 2, // Provisional cart travel multiplier.
  walkSpeed: 5,
  steepPathGradient: 0.25, // More than one half-unit elevation step per tile; provisional.
  pathEnergyFactor: 0.5, // Paths reduce walking fatigue; strength is provisional.
  weedInterval: 10,
  complaintWeedChance: 0.25, // Provisional chance per distinct negative comment.
  wageInterval: 60,
  wage: 12,
  hireCost: 150,
  technicianHireCost: 300,
  technicianWage: 24,
  vendorHireCost: 150,
  vendorWage: 12,
  vendorThirst: 50,
  vendorServiceSeconds: 2,
  turfRepairSeconds: 4,
  crabgrassWear: 4,
  crabgrassDelay: 60,
  carry: 27,
  yardsPerUnit: 4,
  costs: {
    tee: 150,
    green: 250,
    greenTile: 10,
    cup: 0,
    "trim-green": 0,
    fairway: 10,
    firm: 15,
    sand: 20,
    "deep-rough": 5,
    "pot-bunker": 30,
    "waste-bunker": 15,
    brush: 20,
    rocks: 30,
    tree: 75,
    water: 30,
    path: 12,
    rough: 0,
    bench: 80,
    snack: 600,
    "tennis-court": 2200,
    "building-lot": 500,
    marina: 4500,
    church: 4500,
    helipad: 6000,
    airstrip: 14000,
    "swim-club": 2200,
    stable: 2200,
    spa: 2200,
    ballwasher: 100,
    flowerbed: 75,
    hotel: 5000,
    "cart-garage": 2000,
    "pro-shop": 1200,
    "driving-range": 1600,
    "putting-green": 1000,
  },
};
export const TOOLS = [
  "inspect",
  ...LAND_TOOLS,
  "tee",
  "green",
  "cup",
  "trim-green",
  "fairway",
  "firm",
  "sand",
  ...EXTRA_TERRAIN,
  "tree",
  "water",
  "path",
  "rough",
  "bench",
  "snack",
  ...TRAINING_FACILITIES,
  "tennis-court",
  "building-lot",
  "marina",
  "church",
  "helipad",
  "airstrip",
  "swim-club",
  "stable",
  "spa",
  "ballwasher",
  "flowerbed",
  "hotel",
  "cart-garage",
];
