// Qualitative behavior: supplied Interface/parkland.txt (D2).
// Numerical values are provisional and await original-runtime measurements.
export const TERRAIN = {
  tee: {
    name: "Tee",
    color: "#809a4a",
    carry: 1,
    roll: 0.5,
    bounce: 0.25,
    walk: 1,
    preference: 0,
  },
  green: {
    name: "Green",
    color: "#7f9d4e",
    carry: 1,
    roll: 1.1,
    bounce: 0.16,
    walk: 1,
    preference: 1,
  },
  fairway: {
    name: "Fairway",
    color: "#708d42",
    carry: 1,
    roll: 2.5,
    bounce: 0.55,
    walk: 1,
    preference: 5,
  },
  firm: {
    name: "Firm fairway",
    color: "#879653",
    carry: 1,
    roll: 4,
    bounce: 0.85,
    walk: 1,
    preference: 5,
  },
  rough: {
    name: "Rough",
    color: "#5b6f33",
    carry: 0.8,
    roll: 0.5,
    bounce: 0.18,
    walk: 1,
    preference: 0,
  },
  "deep-rough": {
    name: "Deep rough",
    color: "#4e632d",
    carry: 0.5,
    roll: 0.12,
    bounce: 0.08,
    walk: 1.5,
    preference: -6,
  },
  sand: {
    name: "Sand trap",
    color: "#c5bc9c",
    carry: 0.55,
    roll: 0.08,
    bounce: 0.035,
    walk: 1.8,
    preference: -8,
  },
  "pot-bunker": {
    name: "Pot bunker",
    color: "#9d906d",
    carry: 0.3,
    roll: 0.015,
    bounce: 0.01,
    walk: 2.1,
    preference: -14,
  },
  "waste-bunker": {
    name: "Waste bunker",
    color: "#a69776",
    carry: 0.4,
    roll: 0.04,
    bounce: 0.025,
    walk: 1.9,
    preference: -11,
  },
  brush: {
    name: "Brush",
    color: "#556639",
    carry: 0.35,
    roll: 0.07,
    bounce: 0.06,
    walk: 1.8,
    preference: -12,
  },
  tree: {
    name: "Tree",
    color: "#63753a",
    carry: 0.4,
    roll: 0.15,
    bounce: 0.08,
    walk: Infinity,
    preference: -18,
  },
  rocks: {
    name: "Rocks",
    color: "#8a8874",
    carry: 0.45,
    roll: 0.4,
    bounce: 0.8,
    walk: 2.2,
    preference: -13,
  },
  water: {
    name: "Water",
    color: "#589b9c",
    carry: 0,
    roll: 0,
    bounce: 0,
    walk: Infinity,
    preference: -50,
  },
  path: {
    name: "Path",
    color: "#8d8a79",
    carry: 1,
    roll: 3,
    bounce: 0.7,
    walk: 0.45,
    preference: 0,
  },
};
export function terrainRule(type) {
  return TERRAIN[type] || TERRAIN.rough;
}
export const EXTRA_TERRAIN = [
  "deep-rough",
  "pot-bunker",
  "waste-bunker",
  "brush",
  "rocks",
];
