"""Compare mixed-surface candidate trajectories with original x86; flat height/slope helpers supplied."""
from pathlib import Path
import hashlib,json,random,struct,subprocess,sys
import pefile
from unicorn import Uc,UC_ARCH_X86,UC_MODE_32
from unicorn.x86_const import UC_X86_REG_ESP,UC_X86_REG_EAX,UC_X86_REG_FPCW
root=Path(__file__).resolve().parents[2];exe=root/"resources/sim golf/Sid Meier's SimGolf/golf.exe"
assert hashlib.sha256(exe.read_bytes()).hexdigest()=='82838c7e016de83f2ecfa8023ab05896d2666dd83bf2721b863cf239fcc3b7bf'
p=pefile.PE(str(exe));u=Uc(UC_ARCH_X86,UC_MODE_32)
u.mem_map(0x400000,0x100000);u.mem_map(0x839000,0x1000);u.mem_map(0x100000,0x4000)
for a,n in [(0x491380,0x13),(0x491393,0x29),(0x4913e0,0x10b),(0x466b40,0x59),(0x4a57a0,0x27),(0x4baa48,16)]:
 o=p.get_offset_from_rva(a-0x400000);u.mem_write(a,p.__data__[o:o+n])
u.reg_write(UC_X86_REG_FPCW,0x37f);u.reg_write(UC_X86_REG_ESP,0x102000)
u.emu_start(0x491380,0x4913bc,count=20000)
table=list(struct.unpack('<257i',u.mem_read(0x8390ac,257*4)))
path=root/'simgolf-reborn/scene/src/simulation/original-projection-table.js'
source='// Generated by original initializer 0x491380–0x4913bc; last entry is adjacent zero-initialized storage.\nexport const originalProjectionTable=Object.freeze('+json.dumps(table)+');\n'
assert path.read_text()==source,'Projection table differs from original initialization'
u.mem_map(0x530000,0x80000)
for a,n in [(0x421450,0x420),(0x466ba0,0x10e),(0x466a00,0x1d),(0x40a9f0,0x81),(0x40bc50,0x33),(0x4c1870,64)]:
 o=p.get_offset_from_rva(a-0x400000);u.mem_write(a,p.__data__[o:o+n])
from unicorn import UC_HOOK_CODE
from unicorn.x86_const import UC_X86_REG_EIP
u.mem_map(0x820000,0x1000)
for a,n in [(0x421b50,0x8f8),(0x406e80,0x1d0),(0x45ba70,0x60),(0x4b9800,8)]:
 o=p.get_offset_from_rva(a-0x400000);u.mem_write(a,p.__data__[o:o+n])
# Launch fields supplied directly; terrain height and directional slopes are flat.
u.mem_write(0x4235c0,b'\xc3')
for a in [0x42f110,0x40c140]:u.mem_write(a,b'\x31\xc0\xc3')
steps=0;terminal={};published=False
def hook(u,a,s,d):
 global steps,terminal,published
 if a==0x421bde:steps+=1
 if a==0x422401:published=True
 if a==0x422431:
  base=0x577f00+154*256
  terminal={key:struct.unpack('<i',u.mem_read(base+off,4))[0] for off,key in [(0xdc,'x'),(0xe0,'z')]}
u.hook_add(UC_HOOK_CODE,hook)
def write(a,v,size=4):u.mem_write(a,(v&((1<<(size*8))-1)).to_bytes(size,'little'))
def run(q,world):
 global steps,published
 steps=0;published=False;base=0x577f00+154*256
 u.mem_write(base,bytes(264));u.mem_write(0x570d38,bytes(world['grid']))
 u.mem_write(0x53ba00,struct.pack('<2500H',*world['marks']));u.mem_write(0x5608b0,bytes(world['walls']))
 for off,key in [(0xdc,'x'),(0xe0,'z'),(0xe4,'height'),(0xec,'speed'),(0xf0,'verticalSpeed'),(0xe8,'heading'),(0xf4,'angularOffset'),(0x18,'flags')]:write(base+off,q[key])
 write(base+0x21,q['skillMask'],1);write(base+0x20,int(q['professional']),1);write(base+0x1e,q['abilityFlags'],2);write(base+0x101,q['luck'],1)
 write(0x820454,q['seed']);write(0x4c1e0c,q['skillMask']);write(0x5a870c,world['mode']);write(0x5a1f30,world['variant'],1)
 for code,t in world['metadata'].items():
  write(0x576dc0+int(code)*48,t['bounceCoefficient'],1);write(0x576dc1+int(code)*48,t['rollCoefficient'],1)
 original=bytes(u.mem_read(base+8,256))
 u.mem_write(0x102000,struct.pack('<5I',0x400fff,154,0,0,0))
 u.reg_write(UC_X86_REG_ESP,0x102000);u.reg_write(UC_X86_REG_FPCW,0x37f)
 u.emu_start(0x421b50,0x400fff,count=2000000)
 assert u.reg_read(UC_X86_REG_EIP)==0x400fff,'Candidate failed to stop'
 assert bytes(u.mem_read(base+8,256))==original,'Actor was not restored'
 return dict(**terminal,seed=struct.unpack('<I',u.mem_read(0x820454,4))[0],steps=steps,landing=terminal.copy() if published else None)
rng=random.Random(2002)
metadata={code:dict(bounceCoefficient=3,rollCoefficient=0) for code in [2,10,12,13,17]}
world=dict(grid=[rng.choice(list(metadata)) for _ in range(2500)],marks=[rng.choice([0,0,0,32]) for _ in range(2500)],walls=[rng.choice([0,0,0,1,4,16,64]) for _ in range(2500)],metadata=metadata,mode=0,variant=0)
rows=[]
for i in range(150):
 q=dict(x=26112,z=26112,height=0,speed=rng.randrange(1000,4000),verticalSpeed=rng.randrange(256,1000),heading=rng.randrange(2**32),angularOffset=rng.randrange(-100000,100000),flags=rng.choice([0,128,256]),seed=rng.randrange(2**32),professional=bool(rng.randrange(2)),abilityFlags=512,luck=5,skillMask=rng.choice([3,7]))
 world['mode']=i%3;world['variant']=i%4
 rows.append([q,world['mode'],world['variant'],run(q,world)])
module=(root/'simgolf-reborn/scene/src/simulation/original-candidate-step.js').as_uri()
script="""import {readFileSync} from 'node:fs';const {originalCandidateStart,originalCandidateStep}=await import(MODULE);
const {world,rows}=JSON.parse(readFileSync(0,'utf8'));for(const [q,mode,variant,e] of rows){let a=originalCandidateStart(q);
const env={terrainAt:p=>{const i=p.x*50+p.z,code=world.grid[i];return {code,flags:world.marks[i],wallFlags:world.walls[i],...world.metadata[code]};},heightAt:()=>0,slopeAt:()=>0,mode,variant};
for(let i=0;i<2000&&a.speed!==0;i++)a=originalCandidateStep(a,env);
if(a.speed!==0||a.x!==e.x||a.z!==e.z||a.seed!==e.seed||a.steps!==e.steps||JSON.stringify(a.landing)!==JSON.stringify(e.landing))throw Error(JSON.stringify({q,mode,variant,a,e}));}
console.log(`${rows.length} mixed-terrain trajectories and RNG states match original x86.`);
""".replace('MODULE',json.dumps(module))
subprocess.run(['node','--input-type=module','-e',script],input=json.dumps(dict(world=world,rows=rows)),text=True,check=True)
if '--write-fixture' in sys.argv:
 (root/'simgolf-reborn/scene/tests/fixtures/original-candidate-mixed.json').write_text(json.dumps(dict(world=world,rows=rows[:20]+[row for row in rows[20:] if row[3]['landing'] is None]),separators=(',',':'))+'\n')
