"""Compare complete original prospective-route assessor with reconstruction."""
from pathlib import Path
import hashlib,json,random,struct,subprocess,sys
import pefile
from unicorn import Uc,UC_ARCH_X86,UC_MODE_32
from unicorn.x86_const import UC_X86_REG_ESP,UC_X86_REG_EAX,UC_X86_REG_FPCW
root=Path(__file__).resolve().parents[2];exe=root/"resources/sim golf/Sid Meier's SimGolf/golf.exe"
assert hashlib.sha256(exe.read_bytes()).hexdigest()=='82838c7e016de83f2ecfa8023ab05896d2666dd83bf2721b863cf239fcc3b7bf'
p=pefile.PE(str(exe));u=Uc(UC_ARCH_X86,UC_MODE_32)
u.mem_map(0x400000,0x100000);u.mem_map(0x839000,0x1000);u.mem_map(0x100000,0x4000)
for a,n in [(0x491380,0x13),(0x491393,0x29),(0x4913e0,0x10b),(0x466b40,0x59),(0x4a57a0,0x27),(0x4baa48,16)]:
 o=p.get_offset_from_rva(a-0x400000);u.mem_write(a,p.__data__[o:o+n])
u.reg_write(UC_X86_REG_FPCW,0x37f);u.reg_write(UC_X86_REG_ESP,0x102000)
u.emu_start(0x491380,0x4913bc,count=20000)
table=list(struct.unpack('<257i',u.mem_read(0x8390ac,257*4)))
path=root/'simgolf-reborn/scene/src/simulation/original-projection-table.js'
source='// Generated by original initializer 0x491380–0x4913bc; last entry is adjacent zero-initialized storage.\nexport const originalProjectionTable=Object.freeze('+json.dumps(table)+');\n'
assert path.read_text()==source,'Projection table differs from original initialization'
u.mem_map(0x530000,0x80000)
for a,n in [(0x421450,0x420),(0x466ba0,0x10e),(0x466a00,0x1d),(0x40a9f0,0x81),(0x40bc50,0x33),(0x4c1870,64)]:
 o=p.get_offset_from_rva(a-0x400000);u.mem_write(a,p.__data__[o:o+n])
rng=random.Random(2002)
metadata={0:(0,0),1:(-1,0),2:(1,0),3:(2,13),4:(-1,0),17:(2,0),20:(4,0)}
grid=[rng.choice(list(metadata)) for _ in range(2500)]
u.mem_write(0x570d38,bytes(grid))
for code,(cls,kind) in metadata.items():
 u.mem_write(0x576dc2+48*code,bytes([cls&255]));u.mem_write(0x576dc6+48*code,bytes([kind]))
def run(q):
 args=[q['landing']['x'],q['landing']['z'],q['cup']['x'],q['cup']['z'],q['range'],q['shape'],q['flag']]
 u.mem_write(0x102000,struct.pack('<8I',0x400fff,*[v&0xffffffff for v in args]))
 u.reg_write(UC_X86_REG_ESP,0x102000);u.emu_start(0x421450,0x400fff,count=20000)
 return u.reg_read(UC_X86_REG_EAX)
rows=[]
for _ in range(1000):
 q=dict(landing=dict(x=25*1024+rng.randrange(1024),z=25*1024+rng.randrange(1024)),cup=dict(x=rng.randrange(21,30),z=rng.randrange(21,30)),range=rng.randrange(331),shape=rng.choice([-1,0,1]),flag=rng.randrange(2))
 rows.append([q,run(q)])
module=(root/'simgolf-reborn/scene/src/simulation/original-route-assessment.js').as_uri()
script="""import {readFileSync} from 'node:fs';const {originalRouteAssessment}=await import(MODULE);
const {rows,grid,metadata}=JSON.parse(readFileSync(0,'utf8'));
for(const [q,e] of rows){const a=originalRouteAssessment({...q,terrainAt:p=>{const code=grid[p.x*50+p.z];const [shotClass,kind]=metadata[code];return {code,shotClass,kind};}});
 if(a!==e)throw Error(JSON.stringify({q,a,e}));
}console.log(`${rows.length} complete route assessments match original x86.`);
""".replace('MODULE',json.dumps(module))
subprocess.run(['node','--input-type=module','-e',script],input=json.dumps(dict(rows=rows,grid=grid,metadata=metadata)),text=True,check=True)

if '--write-fixture' in sys.argv:
 (root/'simgolf-reborn/scene/tests/fixtures/original-route-assessment.json').write_text(json.dumps(dict(rows=rows[:40],grid=grid,metadata=metadata),separators=(',',':'))+'\n')

# Confirm the design length conversion independently: multiply by 25, divide
# by 25, then store low 16 bits. This corrects the earlier /100 interpretation.
a=0x4135f7;o=p.get_offset_from_rva(a-0x400000);u.mem_write(a,p.__data__[o:o+0x22])
from unicorn.x86_const import UC_X86_REG_ESI
for measure in list(range(10000))+[32767,32768,65535,65536,70710]:
 u.mem_write(0x102014,struct.pack('<I',measure));u.reg_write(UC_X86_REG_ESP,0x102000);u.reg_write(UC_X86_REG_ESI,0)
 u.emu_start(0x4135f7,0x413619,count=50)
 actual=struct.unpack('<h',u.mem_read(0x574504,2))[0]
 expected=(measure+32768)%65536-32768
 assert actual==expected,(measure,actual,expected)
print('10,005 original design length conversions match corrected signed-word storage.')
