"""Initialize original trig table and compare original projection instructions with JS."""
from pathlib import Path
import hashlib,json,random,struct,subprocess,sys
import pefile
from unicorn import Uc,UC_ARCH_X86,UC_MODE_32
from unicorn.x86_const import UC_X86_REG_ESP,UC_X86_REG_EAX,UC_X86_REG_FPCW
root=Path(__file__).resolve().parents[2];exe=root/"resources/sim golf/Sid Meier's SimGolf/golf.exe"
assert hashlib.sha256(exe.read_bytes()).hexdigest()=='82838c7e016de83f2ecfa8023ab05896d2666dd83bf2721b863cf239fcc3b7bf'
p=pefile.PE(str(exe));u=Uc(UC_ARCH_X86,UC_MODE_32)
u.mem_map(0x400000,0x100000);u.mem_map(0x839000,0x1000);u.mem_map(0x100000,0x4000)
for a,n in [(0x491380,0x13),(0x491393,0x29),(0x4913e0,0x10b),(0x466b40,0x59),(0x4a57a0,0x27),(0x4baa48,16)]:
 o=p.get_offset_from_rva(a-0x400000);u.mem_write(a,p.__data__[o:o+n])
u.reg_write(UC_X86_REG_FPCW,0x37f);u.reg_write(UC_X86_REG_ESP,0x102000)
u.emu_start(0x491380,0x4913bc,count=20000)
table=list(struct.unpack('<257i',u.mem_read(0x8390ac,257*4)))
path=root/'simgolf-reborn/scene/src/simulation/original-projection-table.js'
source='// Generated by original initializer 0x491380–0x4913bc; last entry is adjacent zero-initialized storage.\nexport const originalProjectionTable=Object.freeze('+json.dumps(table)+');\n'
if '--write-table' in sys.argv:path.write_text(source)
else:assert path.read_text()==source,'Projection table differs from original initialization'
def run(a,heading,radius):
 u.mem_write(0x102000,struct.pack('<III',0x400fff,heading,radius&0xffffffff))
 u.reg_write(UC_X86_REG_ESP,0x102000);u.emu_start(a,0x400fff,count=200)
 return struct.unpack('<i',struct.pack('<I',u.reg_read(UC_X86_REG_EAX)))[0]
rng=random.Random(2002)
vectors=[(a,r) for a in [0,1,0x3fffffff,0x40000000,0x40000001,0x7fffffff,0x80000000,0xc0000000,0xffffffff] for r in [0,1024,51200,65534,65535,16777214,16777215,2147483647,-1024]]
vectors += [(rng.randrange(2**32),rng.randrange(51201)) for _ in range(10000)]
rows=[[a,r,run(0x466b40,a,r),run(0x466b80,a,r)] for a,r in vectors]
if '--write-table' in sys.argv:
 (root/'simgolf-reborn/scene/tests/fixtures/original-projection.json').write_text(json.dumps(rows[:97],indent=2)+'\n')
module=(root/'simgolf-reborn/scene/src/simulation/original-projection.js').as_uri()
script='''import {readFileSync} from 'node:fs';const {originalProjection}=await import(MODULE);
const rows=JSON.parse(readFileSync(0,'utf8'));
for(const [heading,radius,x,z] of rows){const a=originalProjection(heading,radius);if(a.x!==x||a.z!==z)throw Error(JSON.stringify({heading,radius,x,z,a}));}
console.log(`${rows.length} projection vectors match original x86 with original initialized table.`);
'''.replace('MODULE',json.dumps(module))
subprocess.run(['node','--input-type=module','-e',script],input=json.dumps(rows),text=True,check=True)
