/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false server/worker-configuration.d.ts` (hash: ecb25dc06baf3731ea6e03e3a77b4250)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: "https://simgolfer.0x4d.in";
	COURSE_SCHEDULERS: DurableObjectNamespace<import("./worker").CourseScheduler>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "CourseScheduler";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN">> {}
}
