PRAGMA foreign_keys=ON;
CREATE TABLE players(id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT, created_at INTEGER NOT NULL, role TEXT NOT NULL DEFAULT 'player' CHECK(role IN ('player','admin')), disabled_at INTEGER);
CREATE TABLE identities(provider TEXT NOT NULL, subject TEXT NOT NULL, player_id TEXT NOT NULL REFERENCES players(id), PRIMARY KEY(provider,subject));
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY, player_id TEXT NOT NULL REFERENCES players(id), csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE transactions(state_hash TEXT PRIMARY KEY, provider TEXT NOT NULL, verifier TEXT NOT NULL, nonce TEXT NOT NULL, link_player TEXT, link_session TEXT, expires_at INTEGER NOT NULL);
CREATE TABLE email_codes(id TEXT PRIMARY KEY, email TEXT NOT NULL, code_hash TEXT NOT NULL, browser_hash TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, expires_at INTEGER NOT NULL);
CREATE TABLE rate_limits(key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE saves(player_id TEXT NOT NULL REFERENCES players(id), slot TEXT NOT NULL, body TEXT NOT NULL, revision INTEGER NOT NULL, updated_at INTEGER NOT NULL, PRIMARY KEY(player_id,slot));
CREATE TABLE admin_actions(id INTEGER PRIMARY KEY, actor_id TEXT NOT NULL, target_id TEXT NOT NULL, action TEXT NOT NULL, created_at INTEGER NOT NULL);
